# Generated by Django 5.2 on 2026-08-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Classes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade", models.IntegerField()),
                ("section", models.CharField(max_length=50)),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academicyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academicyear",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.examtype",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.month",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "provence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.province",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("fname", models.CharField(max_length=50)),
                ("gfname", models.CharField(max_length=50)),
                ("card_id", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                ("nationality", models.CharField()),
                ("orignial_zone", models.IntegerField()),
                ("original_village", models.CharField(max_length=50)),
                ("now_zone", models.IntegerField()),
                ("now_village", models.CharField(max_length=50)),
                ("registered_date", models.DateField()),
                ("detached_date", models.DateField()),
                ("phone", models.CharField(max_length=13)),
                (
                    "father_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.job"
                    ),
                ),
                (
                    "mother_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.language",
                    ),
                ),
                (
                    "now_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students_current",
                        to="dashboard.district",
                    ),
                ),
                (
                    "now_province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students_current",
                        to="dashboard.province",
                    ),
                ),
                (
                    "original_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students_original",
                        to="dashboard.district",
                    ),
                ),
                (
                    "original_province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students_original",
                        to="dashboard.province",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("paied", models.IntegerField()),
                ("payment_date", models.DateField()),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academicyear",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.month",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
                ("max_score", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.exam"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("present", models.IntegerField()),
                ("absent", models.IntegerField()),
                ("sick", models.IntegerField()),
                ("excused", models.IntegerField()),
                ("alldays", models.IntegerField()),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academicyear",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.month",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academicyear",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("fname", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=13)),
                ("major", models.CharField(max_length=50)),
                ("years_of_service", models.IntegerField()),
                ("registered_date", models.DateField()),
                ("detached_date", models.DateField()),
                ("graduation_year", models.IntegerField()),
                ("salary", models.IntegerField()),
                ("tax", models.IntegerField()),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.degree",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.job"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.teacher"
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="guidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.teacher"
            ),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
                ("max_score", models.IntegerField()),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academicyear",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.month",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academicyear",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.teacher",
                    ),
                ),
            ],
        ),
    ]
