# Generated by Django 5.2 on 2026-08-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="district",
            old_name="provence",
            new_name="province",
        ),
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=models.CharField(max_length=50),
        ),
    ]
