# Generated by Django 5.2 on 2026-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_provence_district_province_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SideBarCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.IntegerField()),
                ("class_atters", models.CharField(max_length=50)),
            ],
        ),
    ]
