# Generated by Django 5.2 on 2026-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sidebarcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sidebarcategory",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
