# Generated by Django 5.2 on 2026-08-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_sidebarcategory_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SideBarCategory",
        ),
    ]
