# Generated by Django 5.2 on 2026-09-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_delete_sidebarcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="active", max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentclass",
                to="dashboard.student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.status",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.status",
            ),
        ),
    ]
