# Generated by Django 5.2 on 2026-09-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_status_alter_studentclass_student_student_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="orignial_zone",
            new_name="original_zone",
        ),
        migrations.AlterField(
            model_name="student",
            name="detached_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="detached_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
