# Generated by Django 5.2 on 2026-09-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_rename_orignial_zone_student_original_zone_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AcademicYear",
            new_name="AcademiceYear",
        ),
    ]
