# Generated by Django 5.2 on 2026-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_rename_academicyear_academiceyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
