# Generated by Django 5.2 on 2026-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
