# Generated by Django 5.2 on 2026-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="school_id",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
