# Generated by Django 5.2 on 2026-09-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_student_school_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="guidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.teacher",
            ),
        ),
    ]
