# Generated by Django 5.2 on 2026-09-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_classes_guidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("present", models.IntegerField()),
                ("absent", models.IntegerField()),
                ("sick", models.IntegerField()),
                ("excused", models.IntegerField()),
                ("alldays", models.IntegerField()),
                (
                    "present_precent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "academice_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.academiceyear",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.month",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Atendance",
        ),
    ]
