# Generated by Django 5.2 on 2026-09-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_attendance_delete_atendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="present_precent",
            new_name="present_percent",
        ),
    ]
