# Generated by Django 5.2 on 2026-09-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_rename_present_precent_attendance_present_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="alpha_grade",
            field=models.CharField(default="null", max_length=50),
            preserve_default=False,
        ),
    ]
