# Generated by Django 5.2 on 2026-09-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_classes_alpha_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="representative",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assessment",
            name="academice_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.academiceyear",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="classs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.classes"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.month"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.student"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.subject"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="academice_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.academiceyear",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="classs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.classes"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.month"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.student"
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="academice_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.academiceyear",
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="guidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.province"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="academice_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.academiceyear",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="classs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.classes"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.examtype"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.month"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.subject"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.exam"
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.student"
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="academice_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.academiceyear",
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.month"
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.job"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.language"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="now_district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="students_current",
                to="dashboard.district",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="now_province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="students_current",
                to="dashboard.province",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="original_district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="students_original",
                to="dashboard.district",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="original_province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="students_original",
                to="dashboard.province",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.status",
            ),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="academice_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.academiceyear",
            ),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="classs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.classes"
            ),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="studentclass",
                to="dashboard.student",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.degree"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.job"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.status",
            ),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="academice_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.academiceyear",
            ),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="classs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.classes"
            ),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.subject"
            ),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.teacher"
            ),
        ),
    ]
