# Generated by Django 5.2 on 2026-10-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_classes_representative_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalDay",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="classes",
            name="capacity",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="classes",
            name="registered",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="classs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="studentclass",
                to="dashboard.classes",
            ),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="teachersubject",
                to="dashboard.teacher",
            ),
        ),
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hour", models.IntegerField()),
                (
                    "Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.subject",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.classes",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.educationalday",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.teacher",
                    ),
                ),
            ],
        ),
    ]
