# Generated by Django 5.2 on 2026-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0017_educationalday_classes_capacity_classes_registered_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="end_time",
            field=models.TimeField(default="16:00"),
        ),
        migrations.AddField(
            model_name="classes",
            name="start_time",
            field=models.TimeField(default="08:00"),
        ),
        migrations.AddField(
            model_name="classes",
            name="turn",
            field=models.CharField(default="صبح", max_length=50),
        ),
    ]
