# Generated by Django 5.2 on 2026-10-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_classes_end_time_classes_start_time_classes_turn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="representative",
        ),
    ]
