# Generated by Django 5.2 on 2026-10-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_remove_classes_representative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="day",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="Subject",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="classs",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="teacher",
        ),
        migrations.AddField(
            model_name="classes",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.status",
            ),
        ),
        migrations.DeleteModel(
            name="EducationalDay",
        ),
        migrations.DeleteModel(
            name="TimeTable",
        ),
    ]
