# Generated by Django 5.2 on 2026-10-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_remove_timetable_day_remove_timetable_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="registered",
        ),
    ]
